name: external_links
description: A package that provides abstraction to handle external links to your apps with an unified interface.
version: 1.0.0+2
homepage: https://github.com/magicleon94/external_links

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  pedantic: ^1.11.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  bloc_test: ^8.0.0
